-- =============================================
-- V1: Schema completo — Oracle-compatible
-- Ford SpecPulse API — CP3 SOA FIAP 2026
-- =============================================

CREATE TABLE marcas (
    id          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    nome        VARCHAR2(100) NOT NULL,
    slug        VARCHAR2(120) NOT NULL UNIQUE,
    is_ford     NUMBER(1)     DEFAULT 0 NOT NULL,
    criado_em   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_marca_is_ford CHECK (is_ford IN (0, 1))
);

CREATE TABLE veiculos (
    id          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    marca_id    RAW(16) NOT NULL,
    nome        VARCHAR2(150) NOT NULL,
    slug        VARCHAR2(180) NOT NULL UNIQUE,
    segmento    VARCHAR2(50),
    mercado     VARCHAR2(50),
    ano_ini     NUMBER(4),
    ano_fim     NUMBER(4),
    is_ford     NUMBER(1) DEFAULT 0 NOT NULL,
    criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_veiculo_marca FOREIGN KEY (marca_id) REFERENCES marcas(id),
    CONSTRAINT ck_veiculo_is_ford CHECK (is_ford IN (0, 1))
);

CREATE TABLE versoes (
    id           RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    veiculo_id   RAW(16) NOT NULL,
    nome         VARCHAR2(200) NOT NULL,
    slug         VARCHAR2(250) NOT NULL UNIQUE,
    powertrain   VARCHAR2(50),
    tracao       VARCHAR2(50),
    cabine       VARCHAR2(50),
    ano          NUMBER(4),
    criado_em    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_versao_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
);

CREATE TABLE atributos_definicao (
    id          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    codigo      VARCHAR2(100) NOT NULL UNIQUE,
    nome        VARCHAR2(150) NOT NULL,
    categoria   VARCHAR2(80),
    unidade     VARCHAR2(30),
    criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE atributo_sinonimos (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atributo_id     RAW(16) NOT NULL,
    sinonimo        VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_sinonimo_atributo FOREIGN KEY (atributo_id) REFERENCES atributos_definicao(id),
    CONSTRAINT uq_sinonimo UNIQUE (atributo_id, sinonimo)
);

CREATE TABLE especificacoes (
    id                  RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    versao_id           RAW(16) NOT NULL,
    atributo_id         RAW(16) NOT NULL,
    valor               VARCHAR2(500),
    nivel_confianca     VARCHAR2(30) DEFAULT 'CONFIRMADO',
    status              VARCHAR2(30) DEFAULT 'PUBLICADO',
    fonte               VARCHAR2(200),
    criado_em           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_espec_versao    FOREIGN KEY (versao_id)   REFERENCES versoes(id),
    CONSTRAINT fk_espec_atributo  FOREIGN KEY (atributo_id) REFERENCES atributos_definicao(id),
    CONSTRAINT uq_espec           UNIQUE (versao_id, atributo_id)
);

CREATE TABLE comparacoes (
    id                   RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    titulo               VARCHAR2(300),
    referencia_versao_id RAW(16) NOT NULL,
    perfil_cliente       VARCHAR2(50),
    criado_por           RAW(16),
    criado_em            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_comp_versao FOREIGN KEY (referencia_versao_id) REFERENCES versoes(id)
);

CREATE TABLE comparacao_versoes (
    comparacao_id RAW(16) NOT NULL,
    versao_id     RAW(16) NOT NULL,
    PRIMARY KEY (comparacao_id, versao_id),
    CONSTRAINT fk_cv_comparacao FOREIGN KEY (comparacao_id) REFERENCES comparacoes(id),
    CONSTRAINT fk_cv_versao     FOREIGN KEY (versao_id)     REFERENCES versoes(id)
);

CREATE TABLE comparacao_celulas (
    id             RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    comparacao_id  RAW(16) NOT NULL,
    versao_id      RAW(16) NOT NULL,
    atributo_id    RAW(16) NOT NULL,
    valor_snapshot VARCHAR2(500),
    status         VARCHAR2(30),
    CONSTRAINT fk_cel_comparacao FOREIGN KEY (comparacao_id) REFERENCES comparacoes(id),
    CONSTRAINT fk_cel_versao     FOREIGN KEY (versao_id)     REFERENCES versoes(id),
    CONSTRAINT fk_cel_atributo   FOREIGN KEY (atributo_id)   REFERENCES atributos_definicao(id)
);

COMMENT ON TABLE marcas           IS 'Fabricantes de veiculos';
COMMENT ON TABLE veiculos         IS 'Modelos de veiculos por marca';
COMMENT ON TABLE versoes          IS 'Versoes/trims de cada modelo';
COMMENT ON TABLE atributos_definicao IS 'Taxonomia canonica de atributos tecnicos';
COMMENT ON TABLE especificacoes   IS 'Especificacoes tecnicas por versao';
COMMENT ON TABLE comparacoes      IS 'Comparacoes imutaveis Ford vs concorrentes';