-- =============================================
-- V2: Usuarios, refresh tokens e auditoria
-- Oracle-compatible
-- =============================================

CREATE TABLE usuarios (
    id          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    email       VARCHAR2(255) NOT NULL UNIQUE,
    senha_hash  VARCHAR2(255) NOT NULL,
    perfil      VARCHAR2(30)  NOT NULL DEFAULT 'SOMENTE_LEITURA',
    ativo       NUMBER(1)     NOT NULL DEFAULT 1,
    criado_em   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_usuario_ativo  CHECK (ativo IN (0, 1)),
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN (
        'SOMENTE_LEITURA','ANALISTA','GERENTE','VALIDADOR_DADOS','ADMINISTRADOR'
    ))
);

CREATE TABLE refresh_tokens (
    id          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    usuario_id  RAW(16) NOT NULL,
    token_hash  VARCHAR2(255) NOT NULL UNIQUE,
    revogado    NUMBER(1)     NOT NULL DEFAULT 0,
    expira_em   TIMESTAMP     NOT NULL,
    criado_em   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_rt_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT ck_rt_revogado CHECK (revogado IN (0, 1))
);

CREATE TABLE auditoria (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  RAW(16),
    acao        VARCHAR2(100) NOT NULL,
    recurso     VARCHAR2(300),
    status_http NUMBER(3),
    ip          VARCHAR2(50),
    criado_em   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Seed usuarios iniciais (senhas: BCrypt de cada senha listada no README)
-- leitor123 / analista123 / gerente123 / validador123 / admin123
INSERT INTO usuarios (id, email, senha_hash, perfil) VALUES
    (SYS_GUID(), 'leitor@ford.internal',
     '$2a$10$7QJ5cAdS5wG.klwnAZMOTerRrqPsTbvTIOeFh7bUHmcXyH6uh5V4S', 'SOMENTE_LEITURA');
INSERT INTO usuarios (id, email, senha_hash, perfil) VALUES
    (SYS_GUID(), 'analista@ford.internal',
     '$2a$10$i9DCUd1oWE1lsANbE7x6heYRhBgTG.oDpqBrFNBaVQItyAMxR.7nW', 'ANALISTA');
INSERT INTO usuarios (id, email, senha_hash, perfil) VALUES
    (SYS_GUID(), 'gerente@ford.internal',
     '$2a$10$NHnYWxqV0kGVAP1RHq4TuO7ZA9hDrZrF0tJ7MRKA1eMBUJiLbMdJ2', 'GERENTE');
INSERT INTO usuarios (id, email, senha_hash, perfil) VALUES
    (SYS_GUID(), 'validador@ford.internal',
     '$2a$10$LdA1lPJMVFjHnKlQT3FVcuMHuPxWkQ0KH3IfOcHqD7pZ9V6r3YhvS', 'VALIDADOR_DADOS');
INSERT INTO usuarios (id, email, senha_hash, perfil) VALUES
    (SYS_GUID(), 'admin@ford.internal',
     '$2a$10$q.vMt.m9mZe6Kl0k9rN.m.6QR2Xkqs5BXVlFmovLqNfkOw.TUXsOa', 'ADMINISTRADOR');

COMMIT;